name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.5', '1.6']
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1.6
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1.6
